apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-cluster-role
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - nodes
  - pods
  - pods/log
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - endpoints
  - daemonsets
  - deployments
  - replicasets
  - ingresses
  - statefulsets
  - cronjobs
  - jobs
  - horizontalpodautoscalers
  - bindings
  verbs: ["get", "list", "watch"]
